Repository Brun02K20/ISW_2025_4K3_G12, pull requests merged in 2025-09, with the labels that each got.

#7 docs: Se agrega y se actualiza Readme.md
  README.md
Labels: documentation

#12 Fix/add tutorial link
  README.md
Labels: bug, documentation

#16 docs: Agregar ISW_ER_Guía de Trabajos Prácticos Resueltos
  Ejercicios_Resueltos/ISW_ER_Guía de Trabajos Prácticos Resueltos.pdf
Labels: documentation

#20 docs: Agregar ISW_CR_2025_4K3
  ISW_CR_2025_4K3.xlsx
Labels: documentation

#29 docs: cambio definicion ubicacion carpeta Resumenes_Propios
  Plan_Gestion.md
Labels: documentation

#39 chore: agregar carpeta TP014_Restrospectiva
  Entregas/Trabajos_Practicos/TP011_Testing/TP014_Retrospectica/.gitkeep
Labels: documentation

#38 chore: agregar carpeta TP04_SCM - Heramientas de SCM
  Entregas/Trabajos_Practicos/TP04_SCM - Herramientas de SCM/.gitkeep
Labels: documentation

#33 chore/agregar carpetas TP01 y TP02
  Entregas/Trabajos_De_Investigacion/TP01_Poster Cientifico/.gitkeep
  Entregas/Trabajos_De_Investigacion/TP02_Charla Ted/.gitkeep
Labels: documentation

#37 chore: agregar carpeta TP05_SCM - Uso de Repositorio
  Entregas/Trabajos_Practicos/TP05_SCM - Uso de Repositorio/.gitkeep
Labels: documentation

#34 chore: agregar carpeta TP011_Testing
  Entregas/Trabajos_Practicos/TP011_Testing/.gitkeep
Labels: documentation

#45 docs: Actualizar LB
  Plan_Gestion.md
Labels: documentation

#47 docs: agrego archivo pdf de la modalidad academica
  ISW_MA_2025_Planificación Ingeniería y Calidad de Software.pdf
Labels: documentation

#48 Carpeta/agregar unidad1
  Ejercicios_Resueltos/Unidad_1/.gitkeep
  Ejercicios_Resueltos/Unidad_2/.gitkeep
  Ejercicios_Resueltos/Unidad_3/.gitkeep
  Ejercicios_Resueltos/Unidad_4/.gitkeep
  Entregas/Trabajos_Prácticos/.getkeep
  Entregas/Trabajos_Prácticos/ISW_TP_4.pdf
Labels: documentation

#50 docs: Acomodar la estructura del repositorio para marcar linea base.
  Entregas/Investigaciones/.gitkeep
  Entregas/Investigaciones/TP01_Poster Cientifico/.gitkeep
  Entregas/Investigaciones/TP02_Charla Ted/.gitkeep
  Entregas/Trabajos_Practicos/TP4/.gitkeep
  Entregas/Trabajos_Practicos/TP4/ISW_TP_4.pdf
Labels: documentation, enhancement
